name: psmw-rdf
channels:
  - conda-forge
dependencies:
  - python=3.14.2
  - rdflib>=7.4.0
  - pandas>=2.3.3
  - requests>=2.32.5
  - pyyaml>=6.0.3
  - pysftp>=0.2.9
  - pip
  - pip:
      - pyshacl>=0.31.0